### ISSUE TITLE
Outdated version of GCloud

### ISSUE THREAD

**Issue by ahojman** [codeship-library/google-cloud-utilities#25]
https://github.com/codeship-library/google-cloud-utilities/blob/ff9497fe54f0ce328ac31c42e1fc32e207ee9a44/dockercfg-generator/gcr_docker_creds.sh#L16

`gcloud docker` will return the following message when executing:

*WARNING: `gcloud docker` will not be supported for Docker client versions above 18.03. Please use `gcloud auth configure-docker` to configure `docker` to use `gcloud` as a credential helper, then use `docker` as you would for non-GCR registries, e.g. `docker pull gcr.io/project-id/my-image`. Add `--verbosity=error` to silence this warning, e.g. `gcloud docker --verbosity=error -- pull gcr.io/project-id/my-image`. See: https://cloud.google.com/container-registry/docs/support/deprecation-notices#gcloud-docker*

**Comment by joesiewert** [comment]
Thanks @ahojman, will get this updated.

**Comment by ahojman** [comment]
Closed, not seeing any movement around and nobody got assigned. 🤷‍♂️
